pipeline {
    agent any

    environment {
        AWS_REGION            = 'us-east-1'
        CLUSTER_NAME          = 'enterprise-cluster'
        AWS_ACCESS_KEY_ID     = credentials('aws_acces_key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/NaylorRobinson/eks-wordpress-microservice.git',
                        credentialsId: 'github-credentials'
                    ]]
                ])
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'aws eks --region us-east-1 update-kubeconfig --name enterprise-cluster''
                }
            }
        }

        stage('Update Kubeconfig') {
            steps {
                sh 'aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME'
            }
        }

        stage('Deploy with Helm') {
            steps {
                sh 'helm upgrade --install my-microservice ./helm/my-microservice'
            }
        }

        stage('Apply HPA') {
            steps {
                sh 'kubectl apply -f k8s/hpa.yaml'
            }
        }

    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Pipeline failed. Check logs above.'
        }
    }
}
